apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: 
  name: workflows.trinity.cloudlego.com
spec:
  group: trinity.cloudlego.com  
  versions:
    - name: v1     
      served: true     
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                  default: '*/5 * * * *'
                storeartifacts:
                  type: boolean
                  default: false
                tasks:
                  type: array
                  items: 
                    type: object
                    properties:
                      name:
                        type: string
                        pattern: '^[a-zA-Z0-9]*$'
                      command:
                        type: object
                        properties:
                          inline:
                            type: object
                            properties:
                              command:
                                type: string           
                              args:
                                type: array                       
                                items:
                                  type: string
                          script:
                            type: string
            status:
              type: object
              properties:
                runs: 
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      phase:
                        type: string
                      started_at:
                        type: string
                      ended_at:
                        type: string
                      tasks:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            type:
                              type: string
                            status:
                              type: string
                            output:
                              type: string
                            error:
                              type: string
      subresources:     
        status: {}        
  scope: Namespaced
  names:  
    plural: workflows    
    singular: workflow   
    kind: WorkFlow  
    shortNames:
    - wf