apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: workflows.trinity.cloudlego.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: trinity.cloudlego.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                  default: '*/5 * * * *'
                tasks:
                  type: array
                  items: 
                    type: object
                    properties:
                      name:
                        type: string
                        pattern: '^[a-zA-Z0-9]*$'
                      command:
                        type: object
                        properties:
                          inline:
                            type: object
                            properties:
                              command:
                                type: string           
                              args:
                                type: array                       
                                items:
                                  type: string
                          script:
                            type: string
            status:
              type: object
              properties:
                runs: 
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      phase:
                        type: string
                      tasks:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            type:
                              type: string
                            status:
                              type: string
                            output:
                              type: string
                            error:
                              type: string
      subresources:
        # status enables the status subresource.
        status: {}                        
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: workflows
    # singular name to be used as an alias on the CLI and for display
    singular: workflow
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: WorkFlow
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - wf